Wenzel/libmicrovmi

- Cargo.toml
- src/api.rs
- src/bin/main.rs
- src/driver/dummy.rs
- src/driver/mod.rs
- src/driver/xen.rs
- src/lib.rs
Add Xen driver with basic init and pause/resume implementations.
cc @tathanhdinh, if you would like to review the code
Dependencies:
https://github.com/Wenzel/xenctrl
https://github.com/Wenzel/xen-sys (should be renamed to `xenctrl-sys`)
https://github.com/Wenzel/xenstore
https://github.com/Wenzel/xenstore-sys
> Xen driver init

- Cargo.toml
- README.md
- src/api.rs
- src/bin/mem-dump.rs
- src/driver/mod.rs
- src/driver/xen.rs
- src/lib.rs
Conditional compilation of the Xen driver.
cc @tathanhdinh
> xen: add feature xen to conditionally build driver

- README.md
> README: add example how to use mem-dump and API example

- .travis.yml
- src/bin/mem-dump.rs
- src/driver/dummy.rs
- src/driver/kvm.rs
- src/driver/xen.rs
- src/lib.rs
> Add Clippy Integration in Travis

- examples/mem-dump.rs
- src/api.rs
- src/lib.rs
partially solves #7 
it should be good enough for now.
cc @tathanhdinh
> make init driver_type optional, return first matched feature if None

- examples/regs-dump.rs
- src/api.rs
- src/driver/kvm.rs
Read x86 general purpose registers on KVM
> kvm: read registers

- src/driver/xen.rs
There is still an error in line 28 which haven't looked into yet. Maybe you could take a look at it @Wenzel.
> implement register dumping for xen

- .github/workflows/build.yml
- Cargo.toml
- README.md
- examples/pause.rs
- src/api.rs
- src/driver/mod.rs
- src/driver/virtualbox.rs
- src/lib.rs
Add VirtualBox driver based on the fast Debugging Protocol
> Add Virtualbox driver

- .github/workflows/build.yml
integrate https://github.com/KVM-VMI/kvm/pull/30
> actions: use make install rule for libkvmi

- src/driver/kvm.rs
Follow https://github.com/Wenzel/kvmi/pull/13
> kvm: update to kvmi-v6

- .github/workflows/build.yml
Following commit https://github.com/thalium/icebox/commit/bb4f0569bbcc21dd7fe1a7db8b39cfabe7f76637
> actions: VBox FDP is now .cpp

- README.md
Update the README to provide some links on VMI apps, and mention Intel Processor Trace in the VMI API.
cc @rageagainsthepc
> README: add notes on VMI apps and Intel PT

- Cargo.toml
- examples/cr3-events.rs
- src/api.rs
- src/driver/kvm.rs
Started implementing CR3 interception for KVM.
> Kvm intercept cr3

- src/driver/kvm.rs
Implement the missing interception of CR0 and CR4
> kvm: allow interception of all control registers

- .github/workflows/doc.yml
> actions: add doc workflow

- .github/workflows/build.yml
- .github/workflows/security-audit.yml
I have to admit, I am not really willing to deal with the clippy lints for hyper-v. Should I remove the check then or better just don't let it fail?
> Use actions rs

- Cargo.toml
- c_examples/mem-dump.c
- c_examples/pause.c
- c_examples/regs-dump.c
- src/api.rs
- src/capi.rs
- src/driver/dummy.rs
- src/driver/hyperv.rs
- src/driver/kvm.rs
- src/driver/virtualbox.rs
- src/driver/xen.rs
Another box around the box could have spared us a lot of work. ;)
> simplify c api

- examples/msr-events.rs
rework msr-events example
* intercepts 6 MSRs by default
* can specify custom set of MSRs
> examples: msr-events intercepts 6 MSRs by default

- .github/workflows/build.yml
@rageagainsthepc will this fix our CI ?
> actions: do not fail CI upon codecov error

- .github/workflows/build.yml
- .github/workflows/doc.yml
> actions: fix duplicated builds

- Cargo.toml
- src/api.rs
- src/driver/virtualbox.rs
A WIP to read registers on VirtualBox
> Virtualbox: read registers

- Cargo.toml
- README.md
fix #108 
xen driver needs fixing with https://github.com/Wenzel/libmicrovmi/pull/128 first
> Add crates io

- .github/workflows/ci.yml
- README.md
release libmicrovmi on crates.io with github actions
fixes https://github.com/Wenzel/libmicrovmi/issues/73
> ci: publish with github actions

- Cargo.toml
- src/driver/xen.rs
Continued from https://github.com/Wenzel/libmicrovmi/pull/90
> Xen: reading and writing registers

- .github/workflows/ci.yml
fix https://github.com/Wenzel/libmicrovmi/issues/145
> ci: create github release

- .github/workflows/ci.yml
> ci: release debian package

- Cargo.toml
- src/driver/xen.rs
Continue https://github.com/Wenzel/libmicrovmi/pull/98
> Xen: breakpoint

- src/api.rs
- src/driver/kvm.rs
- src/driver/xen.rs
fix https://github.com/Wenzel/libmicrovmi/issues/141
> api: remove mutable buffer parameter from write_physical

- .github/workflows/ci.yml
- examples/cr-events.rs
- examples/interrupt-events.rs
- examples/mem-dump.rs
- examples/mem-events.rs
- examples/msr-events.rs
- examples/pause.rs
- examples/regs-dump.rs
Fix all clippy warnings in examples, and check them in the CI
> ci: compile all examples

- .github/workflows/ci.yml
- .gitpod.Dockerfile
- Cargo.toml
- src/driver/kvm.rs
Following https://github.com/Wenzel/kvmi/pull/40
> cargo: update to kvmi v0.2.4

- src/driver/kvm.rs
fix https://github.com/Wenzel/libmicrovmi/issues/167
> KVM: handle any read size

- Cargo.toml
> cargo: upgrade xenevtchn to v0.1.4

- python/Dockerfile
https://github.com/Wenzel/libmicrovmi/runs/2168613798?check_suite_focus=true
> python: add missing libuuid-devel in Dockerfile

- src/capi/mod.rs
- src/capi/params.rs
- src/driver/memflow.rs
* refactor capi module
* add memflow init params FFI
> capi: add memflow init params FFI

- src/capi/mod.rs
> capi: check null context parameter

- .github/workflows/ci.yml
- python/Dockerfile
shm_open and shm_unlink definitions are there
> ci: FDP on Linux links with rt

- Cargo.toml
fix libloading FDP filename
https://github.com/Wenzel/fdp/pull/18
> cargo: upgrade fdp to 0.2.5

- .github/workflows/ci.yml
- c_examples/.gitignore
- c_examples/CMakeLists.txt
- c_examples/README.md
- c_examples/mem-dump.c
- c_examples/pause.c
- c_examples/regs-dump.c
- doc/src/developer/mem_dump/c.md
libmicrovmi github release for Windows
fix #229
> Windows release

- doc/src/README.md
> doc: fix project status table display

- Cargo.lock
- Cargo.toml
- doc/src/reference/drivers/memflow.md
- doc/src/tutorial/libvmi.md
- python/noxfile.py
- src/api/params.rs
- src/driver/memflow.rs
Also updates libmicrovmi version to 0.3.12
> Update memflow driver for memflow 0.2.1
