Cargo.toml
src/api.rs
src/bin/mem-dump.rs
src/driver/dummy.rs
src/driver/xen.rs

Add incomplete implementation of `read_physical` API
uses `map`/`unmap` pages in `xenforeignmemory`:
https://github.com/Wenzel/xenforeignmemory/blob/master/src/lib.rs#L25

Xen read physical

---

src/api.rs
src/bin/mem-dump.rs
src/driver/dummy.rs
src/driver/kvm.rs
src/driver/xen.rs

I got rid of these hideous `Result<xxx,&str>` that i created at the beginning to use `Box<std::error::Error>`, which should give generic error handling in the trait's functions signatures.

Error handling

---

src/driver/kvm.rs

kvm: fix pause API after update on KMVi v6

---

src/api.rs
src/bin/mem-dump.rs
src/driver/dummy.rs
src/driver/kvm.rs
src/driver/xen.rs
src/lib.rs

rust 1.38.0 deprecates bare traits

deprecate bare traits, use dyn keyword

---

src/api.rs

use unimplemented macro to provide default implementation for Introspectable

---

.github/workflows/build.yml
c_examples/Makefile
c_examples/mem-dump.c
c_examples/regs-dump.c

Following https://github.com/Wenzel/libmicrovmi/pull/43
We should add CI test before merging a PR in the future.
cc @rageagainsthepc

actions: test C API

---

.github/workflows/build.yml

This should fix https://github.com/Wenzel/libmicrovmi/pull/52 not triggering a CI build.

actions: trigger build on PR

---

Cargo.toml
examples/cr-events.rs
examples/cr3-events.rs

@rageagainsthepc this PR adds `clap` command line to `cr-events` example, to pass multiple control registers to watch.
Default is CR3.

Clap cr events

---

Cargo.toml
c_examples/mem-dump.c
c_examples/pause.c
c_examples/regs-dump.c
src/capi.rs

fix #95 
This PR adds a new capi: `microvmi_envlogger_init`, to allow a C program to init the env_logger from C.

add microvmi_envlogger_init

---

codecov.yaml

Thanks to this PR, i found how to fix our codecov CI error:
https://github.com/ros-planning/moveit/pull/1917

codecov: set drop threshold to 10%

---

c_examples/mem-dump.c
c_examples/pause.c
c_examples/regs-dump.c
examples/cr-events.rs
examples/interrupt-events.rs
examples/mem-dump.rs
examples/msr-events.rs
examples/pause.rs
examples/regs-dump.rs
src/api.rs
src/capi.rs
src/driver/dummy.rs
src/driver/hyperv.rs
src/driver/kvm.rs
src/driver/virtualbox.rs
src/driver/xen.rs
src/lib.rs

This PR adds support for additional driver initialization parameters.
This is required for KVM driver, which needs a socket parameter.
Before that it was simply hardcoded to `/tmp/introspector` in the driver.
I added documentation for the new type `DriverInitParam`.
and I converted all examples to the `clap` argument parsing library, so it's easier to support command line parameters in the future.
Naming: what is better:
- `DriverInitParam`
- `DriverInitOption`
- other naming suggestions
:thinking:

Driver init option

---

src/api.rs
src/driver/kvm.rs
src/driver/xen.rs

help fix #111 in Xen
- add definition of IDTR/GDTR (https://xem.github.io/minix86/manual/intel-x86-and-64-manual-vol3/o_fe12b1e2a880e0ce-74.html)
- fetch them in Xen
- fetch them in KVM
regs-dump example (with a little tweak to force get_vcpu_count to 1)

System Table registers (IDTR/GDTR)

---

src/driver/virtualbox.rs

There are no APIs in FDP to fetch the VCPU count, hardcode this for now.

vbox: hardcode VCPU count to 1

---

Cargo.toml

This pins the version of xenstore, to avoid breakage with our last updates on xenstore master

cargo: pin xenstore revision

---

Cargo.toml
src/driver/xen.rs

This should help fix #127 and #125 
Depends on this sub-PR:
https://github.com/Wenzel/xenstore/pull/7

xen: handle permission denied when reading xenstore entries

---

.gitpod.Dockerfile
.gitpod.yml
README.md

Gitpod provides Web IDEs which I think work already really well. I can definitely see myself using those instead of a local IDE (unless I have to actually run the code of course). It should also be handy for new people who want to explore the repo. However, I've enabled experimental features in order to be able to use VSCode instead of Theia because the rust-analyzer plugin does not work with the latter.
Edit: I should mention that experimental features are an account setting unfortunately.

Add gitpod

---

Cargo.toml
src/driver/kvm.rs
src/driver/xen.rs

This PR adds driver specific error types based on `thiserror` for Xen and KVM
regarding virtualbox, the FDP crate returns `Box<dyn Error>` for every function, so implementing a better handling for this driver will start with FDP library.

Driver error enum

---

Cargo.toml

Following https://github.com/Wenzel/libmicrovmi/pull/170#issuecomment-784152381

cargo: upgrade kvmi to v0.3.0

---

.github/workflows/ci.yml
Cargo.toml
build.rs

- Compile Xen, KVM and VirtualBox drivers for debian packaged libmicrovmi.so
- package `libmicrovmi.h` in the Debian package
Note: I'm not a big fan of using `build.rs` to generate a file outside `OUT_DIR` env var, since it's not recommended.
_"In general, build scripts should not modify any files outside of OUT_DIR. It may seem fine on the first blush, but it does cause problems when you use such crate as a dependency, because there's an implicit invariant that sources in .cargo/registry should be immutable. cargo won't allow such scripts when packaging."_
However, I needed to specify a non dynamically configurable path in Cargo-deb's assets field, so I choose this method.

ci: package libmicrovmi.h header in Debian package

---

Cargo.toml
build.rs

fix https://github.com/Wenzel/libmicrovmi/issues/177
There is standard solution avaialble right now, they are discussed on the rust-lang.
This should be considered a workaround in the meantime

cargo: fix location of generated file libmcrovmi.h

---

Cargo.toml
src/driver/virtualbox.rs

Avoid panicking when libFDP.so is not found on the system

vbox: FDP init is now fallible

---

src/api.rs
src/capi.rs
src/driver/hyperv.rs
src/driver/kvm.rs
src/driver/virtualbox.rs
src/driver/xen.rs

In order to solve https://github.com/Wenzel/libmicrovmi/issues/7 for Libvmi, we need to be able to get the concrete `DriverType` from the driver context.

capi: reintroduce get_driver_type

---

src/capi.rs

This fixes a dumb segfault when calling `microvmi_envlogger_init()` multiple times

capi: avoid panicking when env_logger is initialized multiple times

---

.github/workflows/ci.yml
src/lib.rs

The release CI is a bit fragile as it relies on many jobs to work properly.
Move part of this complexity before the release is done to assert they are functional

ci: fix release issues

---

src/lib.rs

clippy: allow upper case acronyms

---

.github/workflows/ci.yml
Cargo.toml
doc/src/reference/drivers.md
python/Cargo.toml
python/microvmi/__init__.py
python/microvmi/volatility/vmi_handler.py
python/noxfile.py
python/src/lib.rs
python/src/params.rs
src/api/mod.rs
src/api/params.rs
src/driver/memflow.rs
src/driver/mod.rs
src/lib.rs
utilities/src/lib.rs

Add support for [memflow](https://github.com/memflow/memflow) driver
Based on PR #201

Add Memflow driver

---

.github/workflows/ci.yml

generated changelog contains all the commits and keeps growing over time
github complains that the request body is too large

ci: remove changelog

---

src/driver/kvm.rs

KVM driver read_physical: bytes_read value was not updated correctly

kvm: fix bytes_read

---

src/driver/virtualbox.rs

Solves: https://github.com/thalium/icebox/issues/38
Related: #188

virtualbox: chunk memory reads by 4K to avoid segfault

---

src/driver/memflow.rs

This PR reuses `init_params.common.vm_name` param when the connector name is `qemu_procfs`, and insert it as `name=value` memflow connector arg.

memflow: use common vm_name init params when available

---

src/capi/params.rs

Declaring the `c_char` init parameters of the CAPI as const makes no sense since they are meant to be alloated and freed.

capi: remove constness of c_char params

---

Cargo.toml

fix unwrap when loading xen libraries:
https://github.com/Wenzel/xenstore/pull/8
https://github.com/Wenzel/xenevtchn/pull/11
https://github.com/Wenzel/xenctrl/pull/41
https://github.com/Wenzel/xenforeignmemory/pull/9

cargo: upgrade xen libraries

---

.github/workflows/ci.yml
Cargo.toml
python/Cargo.toml

- update Cargo.toml to build release with debug info
- update CI jobs which are building public libmicrovmi releases to use the `release` profile

CI: Release with debuginfo

---

python/Cargo.toml

the release profile should only be configured in the root crate

python: remove profile.release section

---

.github/workflows/ci.yml

ci: update to dtolnay/rust-toolchain

---

src/capi/params.rs

As stated in the libmicrovmi documentation, `memflow_connector_args` are optional, however omitting the `memflow_connector_args` from the FFI causes an assertion failure in `std::slice::from_raw_parts`. The documentation for `std::slice::from_raw_parts` states that the pointer must be non-null and properly aligned, since it promises to return a slice that actually refers to valid memory. Prior to these changes, the code would attempt to pass a null pointer via `args_arr` to `std::slice::from_raw_parts` if the optional `memflow_connector_args` were not provided.

Fix FFI handling of optional memflow connector_args
